In [1]:
# Import de Numpy
import numpy as np

In [3]:
# Création d'un tableau Numpy en trois dimensions
array = np.arange(24).reshape(2, 3, 4) #profondeur, hauteur, largeur
array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [8]:
# Création d'un tableau Numpy en deux dimensions
array = np.array([[1, 2 ,3], [4, 5, 6], [7, 8, 9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# Afficher les lignes 2 & 3 et colonne 1 & 2
array[1:3, 0:2] 

array([[4, 5],
       [7, 8]])

In [6]:
# Afficher la deuxième ligne
array[0,:]

array([1, 2, 3])

In [7]:
# Afficher la dernière colonne
array[:,-1]

array([3, 6, 9])

In [9]:
# Afficher true si la valeur est vraie
array == 3

array([[False, False,  True],
       [False, False, False],
       [False, False, False]])

In [10]:
np.tile(1,8)

array([1, 1, 1, 1, 1, 1, 1, 1])

In [19]:
np.zeros((5,5), dtype='float16')

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float16)

In [18]:
np.ones((5,5), dtype='int8')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [17]:
np.diag(np.array([1, 4, 7, 9]))

array([[1, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 7, 0],
       [0, 0, 0, 9]])

In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])