# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [3]:
import numpy as np

#### Q2 : Afficher la version de numpy et la configuration 

#### Q3 : Créer un vecteur nul de taille 10

In [17]:
np.tile(0,10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 4ème place (index 4) du vecteur

In [20]:
array = np.tile(0, 10)
array[3:4] = 1
array

array([0, 0, 0, 4, 0, 0, 0, 0, 0, 0])

In [20]:
array_correction = np.tile(0, 10)
array_correction[3] = 1
array_correction

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0])

#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [22]:
z = np.arange(10, 50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [24]:
np.flip(z)
z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [25]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Q8 : Créer une matrice identié 3x3 

In [6]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

In [7]:
np.random.randint(100, size=(3*3*3)).reshape(3,3, 3)

array([[[81, 26,  5],
        [38, 12, 79],
        [84, 54, 50]],

       [[59, 47, 28],
        [49, 15, 53],
        [27, 33,  1]],

       [[62, 52, 56],
        [53, 83, 48],
        [29, 26, 61]]])

#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [9]:
array = np.random.randint(100, size=(10*10)).reshape(10, 10)
array

array([[86, 41, 82, 45,  6, 89, 50, 83, 74, 97],
       [87,  2, 47, 55,  6, 36, 69, 35, 51, 79],
       [35, 41, 91, 18, 65, 84, 42, 77, 96, 33],
       [93, 87, 17, 71, 92, 16, 48, 97, 99, 54],
       [93, 75, 14,  6, 24, 13, 48, 33, 42, 52],
       [57,  1,  6, 69, 64, 54, 54, 21, 50, 92],
       [90, 21, 48, 11, 31, 94, 29, 31, 78, 20],
       [89, 32, 52, 72, 61, 13, 78, 55,  2, 32],
       [94, 72, 70, 96, 66, 37, 29, 18, 14, 69],
       [ 7, 30, 38, 50, 96, 19, 84, 28, 12, 53]])

In [10]:
np.amax(array)

99

#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

In [11]:
array = np.random.randint(50, size=(5*5)).reshape(5, 5)
np.fill_diagonal(array, [1, 2, 3, 4, 5])
array

array([[ 1, 34,  3,  6, 39],
       [49,  2, 48, 46, 49],
       [44, 34,  3, 30, 30],
       [42, 43,  3,  4, 17],
       [38, 18,  2,  7,  5]])

In [12]:
np.diag(np.array([1, 2, 3, 4, 5]), -1)

array([[0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0]])

#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

In [13]:
np.sum(np.arange(1, 6))

15

#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

In [14]:
np.mean(np.arange(1, 6))

3.0

#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
```python 
l = [x for x in range(11)]
```

In [28]:
l = [x for x in range(11)]
len(l) # tableau une dimension
np.shape(l) # tableau plusieurs dimensions*

(11,)

#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

In [32]:
np.random.rand(10)

array([0.9765928 , 0.20114042, 0.52289105, 0.92996554, 0.29846461,
       0.64888064, 0.32101219, 0.0470731 , 0.75426724, 0.2234249 ])

#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

In [17]:
A = np.arange(10, 15)
B = np.arange(13, 18)
np.array_equal(A ,B)

False

In [ ]:
A = np.arange(10, 15)
B = np.arange(10, 15)
np.array_equal(A ,B)

#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

In [34]:
z = np.arange(10, dtype=np.float32)
z

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [37]:
z.astype(np.int32, copy=False)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type 

#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)