In [2]:
import numpy as np

# Quelques fonctions utiles

On a créé un tableau 2D contenant des valeurs aléatoires. 

In [14]:
rdm_mat = np.random.randint(50, size=(3*5)).reshape(3, 5)
rdm_mat

array([[36, 14,  8, 24, 30],
       [43, 27, 10, 21, 47],
       [28,  6, 15, 33, 42]])

Donner le type de la variable rdm_mat

In [15]:
rdm_mat.dtype

dtype('int64')

Donner la somme des éléments de ce tableau 2D

In [16]:
np.sum(rdm_mat)

384

Faire en sorte de récupérer la valeur maximale sur chaque ligne (sans boucles) avec la fonction np.max

In [17]:
np.max(rdm_mat, axis=1)

array([36, 47, 42])

Faire de même pour récupérer la valeur maximum pour chaque colonne (sans boucles)

In [18]:
np.max(rdm_mat, axis=0)

array([43, 27, 15, 33, 47])

Faire la même chose (max des lignes) en définissant un tableau avec une boucle for et la fonction max de numpy

In [19]:
for cell in rdm_mat:
    np.max(cell, axis=0)

Créer un vecteur aléatoire de taille 100

In [26]:
array = np.random.randint(100, size=(100))
array

array([ 7, 72, 70, 27, 20, 99, 23, 35,  6, 73, 20, 15, 68, 26, 73, 87, 85,
       52, 88, 56, 61, 60, 98,  6, 28,  3, 34, 76, 25,  1,  5, 89, 33, 17,
       70, 41, 46, 26, 46, 35, 49, 24, 96,  4, 88, 18, 17, 30, 87, 91, 49,
       39, 80, 21, 88, 28, 90, 35, 87, 44, 54, 52,  6, 24, 85,  5, 57, 98,
       68, 55, 90,  1, 51, 33, 21, 72,  7, 83, 85, 82, 23, 17, 96, 17, 52,
       39, 59, 30,  5, 40, 74, 99, 98, 72, 85,  2, 39, 16, 58, 63])

Récupérer la position de la valeur maximale du vecteur 

In [27]:
np.argmax(array)

5

Afficher cette valeur 

In [28]:
np.amax(array)

99

Convertir le vecteur en un tableau 10, 10

In [35]:
array = array.reshape(10, 10)
array

array([[ 7, 72, 70, 27, 20, 99, 23, 35,  6, 73],
       [20, 15, 68, 26, 73, 87, 85, 52, 88, 56],
       [61, 60, 98,  6, 28,  3, 34, 76, 25,  1],
       [ 5, 89, 33, 17, 70, 41, 46, 26, 46, 35],
       [49, 24, 96,  4, 88, 18, 17, 30, 87, 91],
       [49, 39, 80, 21, 88, 28, 90, 35, 87, 44],
       [54, 52,  6, 24, 85,  5, 57, 98, 68, 55],
       [90,  1, 51, 33, 21, 72,  7, 83, 85, 82],
       [23, 17, 96, 17, 52, 39, 59, 30,  5, 40],
       [74, 99, 98, 72, 85,  2, 39, 16, 58, 63]])

Calculer la moyenne de chaque ligne de ce tableau (sans boucles)

In [39]:
np.mean(array, axis=1)

array([43.2, 57. , 39.2, 40.8, 50.4, 56.1, 50.4, 52.5, 37.8, 60.6])

Faire un tableau qui contient la moyenne de chaque colonne du tableau 

Calculer la somme de chaque colonne (sans boucles)

In [42]:
# Moyenne de chaque colonne
col_average = np.mean(array, axis=0)

#Somme des valeurs de chaque colonne
np.sum(array, axis=0)

array([432, 468, 696, 247, 610, 394, 457, 481, 555, 540])

Calculer la somme pour chaque ligne (sans boucles)

In [43]:
#Somme des valeurs de chaque ligne
np.sum(array, axis=1)

array([432, 570, 392, 408, 504, 561, 504, 525, 378, 606])